// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuSGyNfa07UMl9Drh1CWtdeEFmOtWr18s',
    appId: '1:392253781988:web:c1ab582c55eb3a738379f1',
    messagingSenderId: '392253781988',
    projectId: 'flash-chat-400e1',
    authDomain: 'flash-chat-400e1.firebaseapp.com',
    storageBucket: 'flash-chat-400e1.appspot.com',
    measurementId: 'G-LMM5B43F8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu35CeaTTT1enDMfvAZDA1H-EBFTCsEc0',
    appId: '1:392253781988:android:a5d1cf7d7068a9c28379f1',
    messagingSenderId: '392253781988',
    projectId: 'flash-chat-400e1',
    storageBucket: 'flash-chat-400e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQLW0NtUkoFzDF9CZYF8un0B2463W1JJ8',
    appId: '1:392253781988:ios:cdcf4fda32a746358379f1',
    messagingSenderId: '392253781988',
    projectId: 'flash-chat-400e1',
    storageBucket: 'flash-chat-400e1.appspot.com',
    iosClientId: '392253781988-4nh93lgb3ffvh6e2rrtrm446a5rr3bss.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQLW0NtUkoFzDF9CZYF8un0B2463W1JJ8',
    appId: '1:392253781988:ios:c9acc5bbe55098078379f1',
    messagingSenderId: '392253781988',
    projectId: 'flash-chat-400e1',
    storageBucket: 'flash-chat-400e1.appspot.com',
    iosClientId: '392253781988-l2lse6mu0oqe7sh6q1st982i660o0moo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
